services:
  app:
    image: mostafa9811/salary_calculation_app:latest
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      MONGO_URI: ${MONGO_URI}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SERVER: ${MAIL_SERVER}
      TESTING: ${TESTING}
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: