name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check pytest version
      run: |
        python -m pip show pytest

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

    - name: Run tests
      env:
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        MAIL_FROM: ${{ secrets.MAIL_FROM }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
        BASE_URL: ${{ secrets.BASE_URL }}
      run: |
        pytest

    - name: Build Docker image
      run: |
        docker build -t mostafa9811/salary_calculation_app .

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push mostafa9811/salary_calculation_app

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Server
      run: |
        ssh root@176.57.184.164 'docker pull mostafa9811/salary_calculation_app:latest && docker-compose up -d'

      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    - name: Notify Deployment
      run: echo "Deployment finished successfully."