name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest

    - name: Build Docker image
      run: |
        docker build -t salary_calculation_app:latest .
        docker tag salary_calculation_app:latest mostafa9811/salary_calculation_app:latest
        docker push mostafa9811/salary_calculation_app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Server
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} root@176.57.184.164 '
          docker pull mostafa9811/salary_calculation_app:latest &&
          docker-compose down &&
          docker-compose up -d
        '
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Notify Deployment
      run: echo "Deployment finished successfully."